name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "* * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "48410066+JadlionHD@users.noreply.github.com"
          git config --local user.name "Hendra Gunawan"
          git add -A
          
          arr[0]="chore: 🎉 auto commit"
          arr[1]="chore: ⚓ auto commit"
          arr[2]="chore: 🌻 auto commit"
          arr[3]="chore: 📡 auto commit"
          arr[4]="chore: 🛰 auto commit"
          arr[5]="chore: 🎇 auto commit"
          arr[6]="chore: 📚 auto commit"
          arr[7]="chore: 🔭 auto commit"
          arr[8]="chore: 💫 auto commit"
          arr[9]="chore: 🥂 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
